"Javascript".lenght();
"PHP".indexOf("P");
"PHP".lastIndexOf("P");
"cobol".toUpperCase();
"ALGOL".toLowerCase;
"Javascript".CharAt(1);
"Javascript".charCodeAt(1)
String.fromCharCode(97);
"Javascript".includes("Java");
"Ruby".startsWith("R");
"Erlang".endsWith("g");
"C++".localeCompare("Ruby");
"Python".localeCompare("Java");
"Javascript".localeCompare("Javascript");
"C++".match(/\+/g);
"Java".search(/a/);
"Javascript".replace("Java", "Ecma");
"Javascript".replace(/a/g, 4);
"Javascript".slice(0, 4);
"Javascript".slice(4);
"Javascript".slice(0, -6);
"Javascript".slice(-6);
"C;Java;Javascript;Ruby".split(";");
"Javascript".substring(4, 0);
"Javascript".substring(4);
"Java".concat("Script");
"Data".concat("Flex");
"Script".padStart(10, "Java");
"C".padEnd(3, "+");
"C".concat("+".repeat(2));
" Self ".trim();
" Scheme ".trimLeft();
" Perl ".trimRight();